//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A3.RouteSearchGraphs.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResource_pt_BR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource_pt_BR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("A3.RouteSearchGraphs.Resources.SharedResource_pt_BR", typeof(SharedResource_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string algorithm {
            get {
                return ResourceManager.GetString("algorithm", resourceCulture);
            }
        }
        
        internal static string heuristic {
            get {
                return ResourceManager.GetString("heuristic", resourceCulture);
            }
        }
        
        internal static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        internal static string cost {
            get {
                return ResourceManager.GetString("cost", resourceCulture);
            }
        }
        
        internal static string expanded_nodes {
            get {
                return ResourceManager.GetString("expanded_nodes", resourceCulture);
            }
        }
        
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        internal static string source {
            get {
                return ResourceManager.GetString("source", resourceCulture);
            }
        }
        
        internal static string target {
            get {
                return ResourceManager.GetString("target", resourceCulture);
            }
        }
        
        internal static string heuristic_kind_manhattan {
            get {
                return ResourceManager.GetString("heuristic_kind_manhattan", resourceCulture);
            }
        }
        
        internal static string heuristic_kind_euclidean {
            get {
                return ResourceManager.GetString("heuristic_kind_euclidean", resourceCulture);
            }
        }
    }
}
